# Generated by Django 5.0.6 on 2024-11-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveBigIntegerField(),
        ),
    ]
